package com.smt.soccerbetrestapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.smt.soccerbetrestapi.utils.TeamCustomConverter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@DynamoDBTable(tableName = "soccer-bet")
@NoArgsConstructor
public class Match {

    private String id;
    private String matchDate;
    private Team homeTeam;
    private Team awayTeam;
    private int homeScore;
    private int awayScore;
    private double winProb;
    private double drawProb;

    public Match(String matchDate, Team homeTeam, Team awayTeam, int homeScore,
                 int awayScore, double winProb, double drawProb) {
        this.matchDate = matchDate;
        this.homeTeam = homeTeam;
        this.awayTeam = awayTeam;
        this.homeScore = homeScore;
        this.awayScore = awayScore;
        this.winProb = winProb;
        this.drawProb = drawProb;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getMatchDate() {
        return matchDate;
    }

    @DynamoDBTypeConverted(converter = TeamCustomConverter.class)
    public Team getHomeTeam() {
        return homeTeam;
    }

    @DynamoDBTypeConverted(converter = TeamCustomConverter.class)
    public Team getAwayTeam() {
        return awayTeam;
    }

    @DynamoDBAttribute
    public int getHomeScore() {
        return homeScore;
    }

    @DynamoDBAttribute
    public int getAwayScore() {
        return awayScore;
    }

    @DynamoDBAttribute
    public double getWinProb() {
        return winProb;
    }

    @DynamoDBAttribute
    public double getDrawProb() {
        return drawProb;
    }

    public void addToTeamMatchStats() {
        homeTeam.addMatchStats(toMatchStats(true));
        awayTeam.addMatchStats(toMatchStats(false));
    }

    private MatchStats toMatchStats(boolean home) {
        String opponent = home ? awayTeam.getName() : homeTeam.getName();
        double localWinProb = home ? this.winProb : 1 - this.winProb - drawProb;
        return new MatchStats(opponent, home, getActualPoints(home), localWinProb, drawProb);
    }

    private int getActualPoints(boolean home) {
        int score1 = home ? homeScore : awayScore;
        int score2 = home ? awayScore : homeScore;
        if (score1 > score2) {
            return 2;
        }
        return score1 < score2 ? 0 : 1;
    }


}
