package com.smt.soccerbetrestapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@DynamoDBTable(tableName = "soccer-bet")
@NoArgsConstructor
public class SimpleMatch {

    private String id;
    private String matchDate;

    public SimpleMatch(String matchDate) {
        this.matchDate = matchDate;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getMatchDate() {
        return matchDate;
    }
}
